alias fslex='dotnet ../../fsLexer/FsLexYacc.11.3.0/build/fslex/net6.0/fslex.dll'
alias fsyacc='dotnet ../../fsLexer/FsLexYacc.11.3.0/build/fsyacc/net6.0/fsyacc.dll '
alias fsi='dotnet fsi -r ../../fsLexer/FsLexYacc.11.3.0/build/fsyacc/net6.0/FsLexYacc.Runtime.dll Util.fs Absyn.fs FunPar.fs FunLex.fs Parse.fs '
alias fsiforreal='dotnet fsi -r ../../fsLexer/FsLexYacc.11.3.0/build/fsyacc/net6.0/FsLexYacc.Runtime.dll Util.fs Absyn.fs FunPar.fs FunLex.fs Parse.fs Fun.fs ParseAndRun.fs '
alias fsihigher='dotnet fsi Absyn.fs HigherFun.fs '
alisa fsiskyhigh= 'dotnet fsi -r ../../fsLexer/FsLexYacc.11.3.0/build/fsyacc/net6.0/FsLexYacc.Runtime.dll Util.fs Absyn.fs FunPar.fs FunLex.fs Parse.fs HigherFun.fs ParseAndRunHigher.fs'